apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-next-js-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-next-js-app
  template:
    metadata:
      labels:
        app: my-next-js-app
    spec:
      containers:
        - name: next-js-container
          image: placeholder/placeholder:tag
          ports:
            - containerPort: 3000
