apiVersion: v1
kind: Service
metadata:
  name: my-next-js-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-next-js-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
