const APP_NAME = 'WAC';
const DEFAULT_POLICY_REDIRECT = '/terms-and-conditions';
const DEFAULT_HOME_REDIRECT = '/';
const DEFAULT_SIGNIN_REDIRECT = '/signin';
const DEFAULT_SIGNUP_REDIRECT = '/signup';
const DEFAULT_VERIFICATION_REDIRECT = '/verify-contact';
const DEFAULT_FORGOT_PASSWORD_REDIRECT = '/forgot-password';
const DEFAULT_RESET_PASSWORD_REDIRECT = '/reset-password';
const DEFAULT_POST_ADS_REDIRECT = '/post';
const DEFAULT_CART_REDIRECT = '/cart';
const DEFAULT_SHOP_REDIRECT = '/shop';

const PAGE_LINKS = [
    {id: 3, name: 'Home', path: DEFAULT_HOME_REDIRECT},
    {id: 5, name: 'Post Ads', path: DEFAULT_POST_ADS_REDIRECT},
    {id: 1, name: 'My Account', path: DEFAULT_SIGNIN_REDIRECT},
];

export {
    APP_NAME,
    PAGE_LINKS,
    DEFAULT_HOME_REDIRECT,
    DEFAULT_POLICY_REDIRECT,
    DEFAULT_SHOP_REDIRECT,
    DEFAULT_SIGNIN_REDIRECT,
    DEFAULT_SIGNUP_REDIRECT,
    DEFAULT_VERIFICATION_REDIRECT,
    DEFAULT_FORGOT_PASSWORD_REDIRECT,
    DEFAULT_RESET_PASSWORD_REDIRECT,
    DEFAULT_POST_ADS_REDIRECT,
    DEFAULT_CART_REDIRECT
};